# Generated by Django 5.2 on 2025-05-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lanlord',
            new_name='landlord',
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(),
        ),
    ]
