# Generated by Django 5.2 on 2025-05-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_lanlord_property_landlord_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS property_property_lanlord_id_e2078b81;",
            reverse_sql="CREATE INDEX property_property_lanlord_id_e2078b81 ON property_property (lanlord_id);"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX property_property_landlord_id_e2078b81 ON property_property (landlord_id);",
            reverse_sql="DROP INDEX IF EXISTS property_property_landlord_id_e2078b81;"
        ),
    ]
